# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ '*' ]
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'
      - '[0-9]*.[0-9]*.[0-9]*-*'
      - '[0-9]*.[0-9]*.[0-9]*\+*'
      - '[0-9]*.[0-9]*.[0-9]*-*\+*'
  pull_request:
    branches: [ 'main' ]

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: enhanced
      - name: Build with Gradle Wrapper
        run: chmod +x gradlew && ./gradlew jpackageImage
      - name: Create tarball
        run: chmod +x build/jpackage/PuzzleSolver/bin/PuzzleSolver && tar -cvf PuzzleSolver-linux.tar.gz build/jpackage/PuzzleSolver
      - name: Upload tar
        uses: actions/upload-artifact@v7
        with:
          path: PuzzleSolver-linux.tar.gz
          archive: false
      - name: Upload zip
        uses: actions/upload-artifact@v7
        with:
          path: build/jpackage/PuzzleSolver
          name: PuzzleSolver-linux.zip

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: enhanced
      - name: Build with Gradle Wrapper
        run: ./gradlew jpackageImage
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          path: build/jpackage/PuzzleSolver
          name: PuzzleSolver-windows.zip

  release:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: [ 'windows', 'linux-x86_64' ]
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Download the artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          skip-decompress: true
      - name: Version Artifacts
        run: |
          for file in PuzzleSolver-*; do
            name="${file}"
            name="${name%.tar.gz}"
            name="${name%.zip}"
            ext="${file#$name}"
            newfile="$name-${{ env.VERSION }}$ext"
            echo "$file->$newfile"
            mv "$file" "$newfile"
          done
          dir
      - name: Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: PuzzleSolver-*.zip, PuzzleSolver-*.tar.gz
          name: Release ${{ env.VERSION }}